name: flutter_anchor
description: A Flutter package for dynamic anchored overlays, including tooltips, popovers, and more
version: 0.0.7
homepage: https://github.com/khoadng/anchor
repository: https://github.com/khoadng/anchor
issue_tracker: https://github.com/khoadng/anchor/issues
topics:
  - tooltip
  - popover
  - context-menu
  - overlay

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  anchor: ^0.0.5
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

