name: anchor
description: A low-level anchoring and positioning package for Dart.
version: 0.0.1
homepage: https://github.com/khoadng/anchor
repository: https://github.com/khoadng/anchor
issue_tracker: https://github.com/khoadng/anchor/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

resolution: workspace

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
